### ISSUE TITLE
Add probability of correct classification (PCC) as an alias for balanced_accuracy

### ISSUE THREAD

**Issue by DoktorMike** [JuliaAI/StatisticalMeasures.jl#15]
Awesome package!

I was wondering if it might be prudent to add another alias to balanced_accuracy called pcc for probability of correct classification.

See the following reference: https://www.kdnuggets.com/2020/03/interpretable-performance-measure-binary-classifier.html#:~:text=Probability%20of%20correct%20classification%20(PCC)&text=PCC%20tells%20us%20how%20good,%2C%20%5B0%2C1%5D.

Not sure how common this alias is.

**Comment by ablaom** [comment]
Thanks for flagging this, @DoktorMike. 

How about we add  the alias `probability_of_correct_classification` for now, to at least improve discoverability?

A short alias like `pcc` has a higher likelihood of conflict with other names a user might want to use, and it doesn't seem to me like the alias is too common. For example, a Wikipedia-specific search of `probability of correct classification` returns only usages out of the present context, but `balanced accuracy` returns plenty.
